# Generated by Django 4.2.7

from django.db import migrations, models
import django.core.validators
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('owner_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('full_name', models.TextField()),
                ('iin', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='IIN must be 12 digits', regex='^\\d{12}$')])),
                ('dob', models.DateField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'owners',
            },
        ),
        migrations.CreateModel(
            name='Insurer',
            fields=[
                ('insurer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'insurers',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vin', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid VIN format', regex='^[A-HJ-NPR-Z0-9]{17}$')])),
                ('make', models.TextField(blank=True, null=True)),
                ('model', models.TextField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('color', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='api.owner')),
            ],
            options={
                'db_table': 'vehicles',
            },
        ),
        migrations.CreateModel(
            name='DriverLicense',
            fields=[
                ('license_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('number', models.TextField(unique=True)),
                ('categories', models.TextField()),
                ('issued_at', models.DateField()),
                ('expires_at', models.DateField()),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('suspended', 'Suspended'), ('revoked', 'Revoked'), ('expired', 'Expired')], max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_licenses', to='api.owner')),
            ],
            options={
                'db_table': 'driver_licenses',
            },
        ),
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('plate_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('plate_number', models.TextField()),
                ('region', models.TextField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plates', to='api.vehicle')),
            ],
            options={
                'db_table': 'plates',
            },
        ),
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('policy_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('policy_number', models.TextField(unique=True)),
                ('type', models.CharField(choices=[('OSAGO', 'OSAGO'), ('KASKO', 'KASKO')], max_length=5)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], max_length=10)),
                ('insurer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.insurer')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_policies', to='api.vehicle')),
            ],
            options={
                'db_table': 'insurance_policies',
            },
        ),
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('accident_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('severity', models.CharField(blank=True, choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('total', 'Total')], max_length=10, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('fault_party', models.CharField(choices=[('owner', 'Owner'), ('other', 'Other'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accidents', to='api.vehicle')),
            ],
            options={
                'db_table': 'accidents',
            },
        ),
        migrations.AddConstraint(
            model_name='plate',
            constraint=models.UniqueConstraint(fields=('plate_number', 'released_at'), name='uq_active_plate'),
        ),
    ]