# Generated by Django 4.2.7 on 2025-09-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accident',
            name='damage_details',
            field=models.JSONField(blank=True, help_text='Список поврежденных деталей', null=True),
        ),
    ]
