# Generated by Django 4.2.7 on 2025-09-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_accident_damage_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarPart',
            fields=[
                ('part_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Название детали', max_length=100, unique=True)),
                ('category', models.CharField(help_text='Категория детали', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Описание детали', null=True)),
            ],
            options={
                'db_table': 'car_parts',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='accident',
            name='damage_details',
        ),
        migrations.AddField(
            model_name='accident',
            name='damaged_parts',
            field=models.ManyToManyField(blank=True, help_text='Поврежденные детали', related_name='accidents', to='api.carpart'),
        ),
    ]
